import type { Meta, StoryObj } from '@storybook/react-vite';
import { useEffect, type ReactNode } from 'react';

import {
  MultitrackEditor,
  useEditorStore,
  type AudioClip,
  type AutomationLane,
  type EditorTrack,
} from '@tahti-player/audio-editor';
import { VisualizerHost } from '@tahti-player/visualizer';

type EditorSeed = {
  tracks: EditorTrack[];
  clips: AudioClip[];
  automationLanes?: AutomationLane[];
};

function ResetEditorStore({
  children,
  seed,
}: {
  children: ReactNode;
  seed?: EditorSeed;
}) {
  useEffect(() => {
    useEditorStore.getState().loadProject(seed ?? { tracks: [], clips: [] });
  }, [seed]);
  return <>{children}</>;
}

const seedTrack = (id: string, name: string, color: string): EditorTrack => ({
  id,
  name,
  nameAutoGenerated: false,
  volume: 0.8,
  pan: 0,
  mute: false,
  solo: false,
  color,
});

const seedClip = (trackId: string, color: string): AudioClip => ({
  id: `${trackId}-clip`,
  trackId,
  label: 'Sketch',
  audioBlob: new Blob([], { type: 'audio/wav' }),
  mimeType: 'audio/wav',
  sourceDuration: 12,
  offsetIntoSource: 0,
  durationSec: 12,
  startSec: 0,
  color,
  peaks: Float32Array.from(
    { length: 240 },
    (_, i) => Math.abs(Math.sin(i / 7)) * 0.8,
  ),
});

const automationSeed: EditorSeed = {
  tracks: [
    seedTrack('drums', 'Drums', '#f59e0b'),
    seedTrack('pad', 'Pad', '#8b5cf6'),
  ],
  clips: [seedClip('drums', '#f59e0b'), seedClip('pad', '#8b5cf6')],
  automationLanes: [
    {
      id: 'drums-vol',
      target: { kind: 'trackVolume', trackId: 'drums' },
      enabled: true,
      points: [
        { t: 0, v: 0 },
        { t: 2, v: 0.9 },
        { t: 8, v: 0.9 },
        { t: 11, v: 0.2 },
      ],
    },
    {
      id: 'pad-pan',
      target: { kind: 'trackPan', trackId: 'pad' },
      enabled: true,
      points: [
        { t: 0, v: -0.8 },
        { t: 6, v: 0.8 },
        { t: 12, v: -0.8 },
      ],
    },
  ],
};

const meta = {
  title: 'Audio/MultitrackEditor',
  component: MultitrackEditor,
  parameters: {
    layout: 'padded',
  },
  decorators: [
    (Story, ctx) => (
      <div className="bg-background text-foreground min-h-96 w-full max-w-6xl">
        <ResetEditorStore
          seed={ctx.parameters.editorSeed as EditorSeed | undefined}
        >
          <Story />
        </ResetEditorStore>
      </div>
    ),
  ],
} satisfies Meta<typeof MultitrackEditor>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Empty: Story = {
  args: {
    showVizSlot: true,
    vizSlot: <VisualizerHost className="h-full min-h-64 w-full" />,
    onBounce: async () => undefined,
  },
};

export const ArrangeOnly: Story = {
  args: {
    showVizSlot: false,
    onBounce: async () => undefined,
  },
};

/** Volume and pan lanes: click a lane to add a point, drag to move it,
 *  double-click or Delete to remove it. */
export const AutomationLanes: Story = {
  args: {
    showVizSlot: false,
    onBounce: async () => undefined,
  },
  parameters: { editorSeed: automationSeed },
};
