import type { StudioSound } from '../studio-types';

export const mockSoundStore: StudioSound[] = [
  {
    id: 'arch-mock-1',
    title: 'Northern Lights — Live Set',
    status: 'READY',
    durationSec: 3720,
    description: 'Mock archive item for studio POC.',
    genre: 'ambient',
    contentType: 'DJ_SET',
    isPublic: true,
    visibility: 'PUBLIC',
    releaseDate: '2026-07-15',
    downloadsEnabled: true,
    commentsEnabled: true,
    pinnedAt: '2026-07-15T12:00:00.000Z',
    createdAt: new Date().toISOString(),
    peaks: Array.from({ length: 96 }, (_, i) =>
      Math.round(60 + 120 * Math.abs(Math.sin(i * 0.37))),
    ),
    tracklist: [
      {
        id: 'mix-track-1',
        title: 'Aurora Drift',
        artist: 'Northern Lights',
        startSec: 0,
      },
      {
        id: 'mix-track-2',
        title: 'Midnight Broadcast',
        artist: 'Northern Lights',
        startSec: 900,
      },
      {
        id: 'mix-track-3',
        title: 'Kaamos Bloom',
        artist: 'Northern Lights',
        startSec: 1800,
      },
    ],
    tracklistOverlay: { enabled: true, preset: 'cards' },
  },
  {
    id: 'arch-mock-2',
    title: 'Studio sketch A',
    status: 'READY',
    durationSec: 214,
    genre: 'electronic',
    contentType: 'TRACK',
    isPublic: false,
    visibility: 'PRIVATE',
    releaseDate: null,
    downloadsEnabled: false,
    commentsEnabled: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'arch-mock-3',
    title: 'Imported from hearthis.at',
    status: 'READY',
    durationSec: 2640,
    genre: 'house',
    contentType: 'DJ_SET',
    isPublic: true,
    visibility: 'PUBLIC',
    releaseDate: null,
    downloadsEnabled: false,
    commentsEnabled: true,
    createdAt: new Date().toISOString(),
    embedProvider: 'HEARTHIS',
    embedUri: '1234567',
  },
];
