blank_issues_enabled: false
contact_links:
  - name: Features, bug reports, questions
    url: https://github.com/janiluuk/tahti-player/discussions
    about: Please use Discussions for feature requests, bug reports, and questions.
  - name: Contributing guidelines
    url: https://github.com/janiluuk/tahti-player/blob/master/packages/docs/development/contributing.md
    about: Issues and PRs are not accepted. Please read the contribution guidelines above.
