/* eslint-disable */
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	libraryList: (search: string, offset: number, filter: {
	kind: FacetKind,
	value: string,
	/**  Album artist, for `Albums`. */
	secondary: string | null,
} | null, sort: {
	column: SortColumn,
	descending: boolean,
} | null) => typedError<LibraryPage, string>(__TAURI_INVOKE("library_list", { search, offset, filter, sort })),
	libraryFacets: (kind: FacetKind) => typedError<FacetGroup[], string>(__TAURI_INVOKE("library_facets", { kind })),
	libraryMatchingIds: (search: string, filter: {
	kind: FacetKind,
	value: string,
	/**  Album artist, for `Albums`. */
	secondary: string | null,
} | null, sort: {
	column: SortColumn,
	descending: boolean,
} | null) => typedError<string[], string>(__TAURI_INVOKE("library_matching_ids", { search, filter, sort })),
	/**
	 *  Verifies and orders a batch of tracks for the player and grants the
	 *  asset protocol access to each file (same as `library_resolve`, in bulk).
	 */
	libraryPreparePlayback: (ids: string[]) => typedError<PlaybackBatch, string>(__TAURI_INVOKE("library_prepare_playback", { ids })),
	libraryTotals: () => typedError<LibraryTotals, string>(__TAURI_INVOKE("library_totals")),
	libraryImport: () => typedError<ImportResult, string>(__TAURI_INVOKE("library_import")),
	libraryImportFolder: () => typedError<ImportResult, string>(__TAURI_INVOKE("library_import_folder")),
	/**
	 *  Imports an explicit list of files/folders -- the entry point for native
	 *  drag-drop, which hands over absolute paths directly rather than going
	 *  through a picker dialog. Directories are walked the same way folder
	 *  import does; unsupported files are counted as skipped, not errored.
	 */
	libraryImportPaths: (paths: string[]) => typedError<ImportResult, string>(__TAURI_INVOKE("library_import_paths", { paths })),
	/**
	 *  Interrupts the in-flight import loop before its next file. Checked
	 *  cooperatively, so a file already being read/inserted still completes.
	 */
	libraryImportCancel: () => typedError<null, string>(__TAURI_INVOKE("library_import_cancel")),
	libraryResolve: (id: string) => typedError<string, string>(__TAURI_INVOKE("library_resolve", { id })),
	libraryRemove: (id: string) => typedError<null, string>(__TAURI_INVOKE("library_remove", { id })),
	libraryRemoveMany: (ids: string[]) => typedError<number, string>(__TAURI_INVOKE("library_remove_many", { ids })),
	/**
	 *  Reveals a track's original file in the OS file manager. Calls the
	 *  opener plugin's Rust API directly (`app.opener()`, bypassing the
	 *  IPC-scoped `reveal-item-in-dir` permission the same way `library_resolve`
	 *  bypasses the asset-protocol scope with a per-path `allow_file`) since the
	 *  user already granted access to this exact file by importing it -- a
	 *  static allow-list can't cover arbitrary import locations.
	 */
	libraryReveal: (id: string) => typedError<null, string>(__TAURI_INVOKE("library_reveal", { id })),
	libraryListUnavailable: () => typedError<LibraryTrack[], string>(__TAURI_INVOKE("library_list_unavailable")),
	libraryRescan: () => typedError<LibraryTrack[], string>(__TAURI_INVOKE("library_rescan")),
	libraryRelink: (id: string) => typedError<{
	id: string,
	path: string,
	title: string,
	artist: string,
	album: string,
	format: string,
	duration: number | null,
	sampleRate: number,
	channels: number,
	bitsPerSample: number | null,
	sizeBytes: number,
	available: boolean,
	unavailableSince: string | null,
	albumArtist: string,
	trackNo: number | null,
	discNo: number | null,
	year: number | null,
	genre: string,
	comment: string,
	bitrateKbps: number | null,
	/**
	 *  When the track first entered the catalog (UTC, `YYYY-MM-DD HH:MM:SS`).
	 *  Filled by the database, so extraction leaves it empty.
	 */
	addedAt: string,
} | null, string>(__TAURI_INVOKE("library_relink", { id })),
	libraryListRoots: () => typedError<LibraryRoot[], string>(__TAURI_INVOKE("library_list_roots")),
	/**
	 *  Folder picker -> register as root -> initial scan (imports everything
	 *  under it, tagged to the root).
	 */
	libraryAddRoot: () => typedError<{
	imported: number,
	skipped: number,
	/**  Known tracks whose file is no longer there. */
	missing: number,
	/**  Previously-missing tracks whose file is back. */
	recovered: number,
	errors: ImportFailure[],
	cancelled: boolean,
} | null, string>(__TAURI_INVOKE("library_add_root")),
	libraryRemoveRoot: (id: string) => typedError<null, string>(__TAURI_INVOKE("library_remove_root", { id })),
	/**
	 *  Re-scans every root: imports files that appeared since the last scan and
	 *  refreshes missing/recovered state. Idempotent -- a second run with no
	 *  filesystem changes imports and changes nothing.
	 */
	libraryRescanRoots: () => typedError<RootScanResult, string>(__TAURI_INVOKE("library_rescan_roots")),
	libraryRelinkRoot: (id: string) => typedError<{
	root: LibraryRoot,
	/**  Tracks re-pointed at the new folder (same relative path and size). */
	relinked: number,
	/**  Tracks with no proven match in the new folder; left untouched. */
	unmatched: number,
} | null, string>(__TAURI_INVOKE("library_relink_root", { id })),
	isFlatpak: () => __TAURI_INVOKE<boolean>("is_flatpak"),
	copyDirRecursive: (from: string, to: string) => typedError<null, string>(__TAURI_INVOKE("copy_dir_recursive", { from, to })),
	extractZip: (zipPath: string, destPath: string) => typedError<null, string>(__TAURI_INVOKE("extract_zip", { zipPath, destPath })),
	downloadFile: (url: string, destPath: string) => typedError<null, string>(__TAURI_INVOKE("download_file", { url, destPath })),
	httpFetch: (request: HttpRequest) => typedError<HttpResponse, string>(__TAURI_INVOKE("http_fetch", { request })),
	ytdlpSearch: (query: string, maxResults: number | null) => typedError<YtdlpSearchResult[], string>(__TAURI_INVOKE("ytdlp_search", { query, maxResults })),
	ytdlpGetStream: (videoId: string) => typedError<YtdlpStreamInfo, string>(__TAURI_INVOKE("ytdlp_get_stream", { videoId })),
	ytdlpGetPlaylist: (url: string) => typedError<YtdlpPlaylistInfo, string>(__TAURI_INVOKE("ytdlp_get_playlist", { url })),
	getStartupLogs: () => __TAURI_INVOKE<StartupLogEntry[]>("get_startup_logs"),
	mcpStart: () => typedError<number, string>(__TAURI_INVOKE("mcp_start")),
	mcpStop: () => typedError<null, string>(__TAURI_INVOKE("mcp_stop")),
	httpApiStart: () => typedError<HttpApiStartResult, string>(__TAURI_INVOKE("http_api_start")),
	httpApiStop: () => typedError<null, string>(__TAURI_INVOKE("http_api_stop")),
	mpdStart: () => typedError<number, string>(__TAURI_INVOKE("mpd_start")),
	mpdStop: () => typedError<null, string>(__TAURI_INVOKE("mpd_stop")),
	streamServerPort: () => __TAURI_INVOKE<number>("stream_server_port"),
	ytdlpEnsureInstalled: () => typedError<boolean, string>(__TAURI_INVOKE("ytdlp_ensure_installed")),
	discordConnect: () => typedError<null, string>(__TAURI_INVOKE("discord_connect")),
	discordDisconnect: () => typedError<null, string>(__TAURI_INVOKE("discord_disconnect")),
	discordSetActivity: (track: TrackPresence) => typedError<boolean, string>(__TAURI_INVOKE("discord_set_activity", { track })),
	discordClearActivity: () => typedError<boolean, string>(__TAURI_INVOKE("discord_clear_activity")),
	bridgeRespond: (response: BridgeResponse) => typedError<null, string>(__TAURI_INVOKE("bridge_respond", { response })),
	bridgeNotify: (notification: BridgeNotification) => typedError<null, string>(__TAURI_INVOKE("bridge_notify", { notification })),
	historyRecordEvent: (event: PlayEvent) => typedError<null, string>(__TAURI_INVOKE("history_record_event", { event })),
	historyFetch: (page: PageRequest) => typedError<Page<HistoryEntry>, string>(__TAURI_INVOKE("history_fetch", { page })),
	historyDeleteRange: (range: TimeRange) => typedError<null, string>(__TAURI_INVOKE("history_delete_range", { range })),
	historyHourlyListeningTime: (range: TimeRange) => typedError<HourlyListeningTime, string>(__TAURI_INVOKE("history_hourly_listening_time", { range })),
	historyDailyListeningTime: (range: TimeRange) => typedError<DailyListeningTime[], string>(__TAURI_INVOKE("history_daily_listening_time", { range })),
	historyFirstPlayAt: () => typedError<{
	at: number,
} | null, string>(__TAURI_INVOKE("history_first_play_at")),
	historyTopArtists: (range: TimeRange, limit: number) => typedError<TopArtist[], string>(__TAURI_INVOKE("history_top_artists", { range, limit })),
	historyTopAlbums: (range: TimeRange, limit: number) => typedError<TopAlbum[], string>(__TAURI_INVOKE("history_top_albums", { range, limit })),
	historyTopTracks: (range: TimeRange, limit: number) => typedError<TopTrack[], string>(__TAURI_INVOKE("history_top_tracks", { range, limit })),
};

/* Types */
export type BridgeNotification = {
	subsystem: string,
};

export type BridgeResponse = {
	traceId: string,
} & BridgeResponseBody;

export type BridgeResponseBody = { status: "success"; data: unknown } | { status: "error"; error: string };

export type DailyListeningTime = {
	date: string,
	value: number,
};

/**  Narrows the track list to one group from `library_facets`. */
export type FacetFilter = {
	kind: FacetKind,
	value: string,
	/**  Album artist, for `Albums`. */
	secondary: string | null,
};

/**  One group in a browse tab. For albums `secondary` is the album artist. */
export type FacetGroup = {
	name: string,
	secondary: string,
	year: number | null,
	trackCount: number,
	durationSec: number | null,
	sizeBytes: number,
};

/**  What a browse tab groups by. */
export type FacetKind = "artists" | "albums" | "genres" | "folders";

export type FirstPlay = {
	at: number,
};

export type HistoryEntry = {
	playId: string,
	title: string,
	artists: string[],
	albumTitle: string | null,
	durationMs: number | null,
	artworkUrl: string | null,
	provider: string | null,
	providerId: string | null,
	startedAt: number,
	msPlayed: number,
	endReason: PlayEndReason | null,
	endPositionMs: number | null,
};

export type HourlyListeningTime = {
	values: number[],
};

export type HttpApiStartResult = {
	port: number,
	lan_address: string | null,
};

export type HttpRequest = {
	url: string,
	method: string | null,
	headers: { [key in string]: string } | null,
	body: string | null,
};

export type HttpResponse = {
	status: number,
	headers: { [key in string]: string },
	body: string,
};

export type ImportFailure = {
	path: string,
	error: string,
};

export type ImportResult = {
	imported: number,
	/**
	 *  Files walked (folder import / drag-drop) that were neither imported
	 *  nor errored -- unsupported extensions, silently ignored before this
	 *  counter existed.
	 */
	skipped: number,
	errors: ImportFailure[],
	/**
	 *  True when `library_import_cancel` interrupted the loop before every
	 *  path was processed. Paths not yet reached are neither imported,
	 *  skipped nor counted as errors.
	 */
	cancelled: boolean,
};

export type LibraryPage = {
	tracks: LibraryTrack[],
	total: number,
};

/**
 *  A folder the user asked the library to keep in sync. `track_count` /
 *  `missing_count` are aggregated on read; `available` is whether the folder
 *  itself currently exists on disk (false for a disconnected drive).
 */
export type LibraryRoot = {
	id: string,
	path: string,
	createdAt: string,
	lastScannedAt: string | null,
	trackCount: number,
	missingCount: number,
	available: boolean,
};

/**
 *  Everything in the catalog, for the "on this device" totals line --
 *  deliberately separate from cloud storage usage.
 */
export type LibraryTotals = {
	trackCount: number,
	durationSec: number | null,
	sizeBytes: number,
};

export type LibraryTrack = {
	id: string,
	path: string,
	title: string,
	artist: string,
	album: string,
	format: string,
	duration: number | null,
	sampleRate: number,
	channels: number,
	bitsPerSample: number | null,
	sizeBytes: number,
	available: boolean,
	unavailableSince: string | null,
	albumArtist: string,
	trackNo: number | null,
	discNo: number | null,
	year: number | null,
	genre: string,
	comment: string,
	bitrateKbps: number | null,
	/**
	 *  When the track first entered the catalog (UTC, `YYYY-MM-DD HH:MM:SS`).
	 *  Filled by the database, so extraction leaves it empty.
	 */
	addedAt: string,
};

export type Page<T> = {
	items: T[],
	total: number,
};

export type PageRequest = {
	limit: number,
	offset: number,
};

export type PlayEndReason = "finished" | "skipped" | "stopped";

export type PlayEvent = {
	playId: string,
	kind: PlayEventKind,
	at: number,
	positionMs: number,
	seekToMs: number | null,
	snapshot: TrackSnapshot | null,
};

export type PlayEventKind = "started" | "paused" | "resumed" | "seeked" | "finished" | "skipped" | "stopped";

export type PlaybackBatch = {
	/**  Playable tracks, in the order the ids were given. */
	items: PlaybackItem[],
	/**  Requested tracks whose file is missing (now persisted as unavailable). */
	unavailable: number,
};

/**  A track ready to hand to the player: its row plus the verified file path. */
export type PlaybackItem = {
	track: LibraryTrack,
	path: string,
};

export type RelinkRootResult = {
	root: LibraryRoot,
	/**  Tracks re-pointed at the new folder (same relative path and size). */
	relinked: number,
	/**  Tracks with no proven match in the new folder; left untouched. */
	unmatched: number,
};

/**
 *  Outcome of scanning one or more roots: new files imported, plus how many
 *  already-known tracks changed availability.
 */
export type RootScanResult = {
	imported: number,
	skipped: number,
	/**  Known tracks whose file is no longer there. */
	missing: number,
	/**  Previously-missing tracks whose file is back. */
	recovered: number,
	errors: ImportFailure[],
	cancelled: boolean,
};

/**
 *  Sortable track-table columns. A closed enum, never user text, so the
 *  ORDER BY below is assembled from fixed SQL only.
 */
export type SortColumn = "title" | "artist" | "album" | "genre" | "year" | "trackNo" | "duration" | "format" | "size" | "bitrate" | "added";

export type StartupLogEntry = {
	timestamp: string,
	level: string,
	message: string,
};

export type TimeRange = {
	from: number,
	to: number,
};

export type TopAlbum = {
	title: string,
	artist: string,
	artworkUrl: string | null,
	msPlayed: number,
	plays: number,
};

export type TopArtist = {
	name: string,
	artworkUrl: string | null,
	msPlayed: number,
	plays: number,
};

export type TopTrack = {
	title: string,
	artists: string[],
	artworkUrl: string | null,
	msPlayed: number,
	plays: number,
};

export type TrackPresence = {
	title: string,
	artist: string,
	album: string | null,
	artworkUrl: string | null,
	startTimestamp: number | null,
	endTimestamp: number | null,
};

export type TrackSnapshot = {
	title: string,
	artists: string[],
	albumTitle: string | null,
	durationMs: number | null,
	artworkUrl: string | null,
	provider: string,
	providerId: string,
};

export type TrackSort = {
	column: SortColumn,
	descending: boolean,
};

export type YtdlpPlaylistEntry = {
	id: string,
	title: string,
	duration: number | null,
	thumbnails: YtdlpThumbnail[],
	channel: string | null,
};

export type YtdlpPlaylistInfo = {
	id: string,
	title: string,
	entries: YtdlpPlaylistEntry[],
};

export type YtdlpSearchResult = {
	id: string,
	title: string,
	duration: number | null,
	thumbnail: string | null,
	channel: string | null,
};

export type YtdlpStreamInfo = {
	stream_url: string,
	duration: number | null,
	title: string | null,
	container: string | null,
	codec: string | null,
};

export type YtdlpThumbnail = {
	url: string,
	width: number | null,
	height: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

