import { describe, expect, it } from 'vitest';

import { RACK_EFFECTS } from '@tahti-player/audio-rack';

import { useEditorStore } from './state/editorStore';

describe('audio-editor package surface', () => {
  it('starts with loadProject and addTrack helpers', () => {
    const st = useEditorStore.getState();
    expect(typeof st.loadProject).toBe('function');
    expect(typeof st.addTrack).toBe('function');
    expect(typeof st.addMasterEffect).toBe('function');
  });

  it('shares the rack catalog with audio-rack', () => {
    expect(RACK_EFFECTS.length).toBeGreaterThanOrEqual(19);
  });

  it('updateTrack changes volume and pan for Multitrack faders', () => {
    useEditorStore.getState().loadProject({
      tracks: [
        {
          id: 't1',
          name: 'Lead',
          nameAutoGenerated: false,
          volume: 0.5,
          pan: 0,
          mute: false,
          solo: false,
          color: '#3b82f6',
        },
      ],
      clips: [],
    });
    useEditorStore.getState().updateTrack('t1', { volume: 0.8, pan: -0.25 });
    const track = useEditorStore.getState().tracks[0];
    expect(track?.volume).toBeCloseTo(0.8, 5);
    expect(track?.pan).toBeCloseTo(-0.25, 5);
    useEditorStore.getState().loadProject({ tracks: [], clips: [] });
  });
});
