import { describe, expect, it } from 'vitest';

import {
  automationFromTimeline,
  gainDbToVolume,
  timelineHasClips,
  toEditorTimeline,
  volumeToGainDb,
} from './editorTimelineAdapter';

describe('editorTimelineAdapter', () => {
  it('round-trips volume through gainDb within a step', () => {
    for (const vol of [0.25, 0.5, 0.8, 1]) {
      const back = gainDbToVolume(volumeToGainDb(vol));
      expect(Math.abs(back - vol)).toBeLessThan(0.08);
    }
  });

  it('serializes tracks and clips with the default sound id', () => {
    const timeline = toEditorTimeline(
      {
        tracks: [
          {
            id: 't1',
            name: 'Lead',
            nameAutoGenerated: false,
            volume: 0.8,
            pan: 0,
            mute: false,
            solo: false,
            color: '#abc',
          },
        ],
        clips: [
          {
            id: 'c1',
            trackId: 't1',
            startSec: 1,
            durationSec: 4,
            offsetIntoSource: 0.5,
            sourceDuration: 10,
            audioBlob: new Blob(),
            mimeType: 'audio/wav',
            peaks: new Float32Array(),
            label: 'Lead',
            color: '#abc',
            sourceKind: 'audio',
          },
        ],
      },
      'sound-1',
    );
    expect(timeline.tracks).toHaveLength(1);
    expect(timeline.tracks[0]?.clips[0]?.sourceSoundId).toBe('sound-1');
    expect(timeline.tracks[0]?.clips[0]?.startSec).toBe(1);
    expect(timeline.durationSec).toBeGreaterThanOrEqual(5);
    expect(timelineHasClips(timeline)).toBe(true);
    expect(timelineHasClips({ version: 1, durationSec: 1, tracks: [] })).toBe(
      false,
    );
  });

  it('round-trips automation lanes through the synced timeline JSON', () => {
    const track = {
      id: 't1',
      name: 'Lead',
      nameAutoGenerated: false,
      volume: 0.8,
      pan: 0,
      mute: false,
      solo: false,
      color: '#abc',
    };
    const automationLanes = [
      {
        id: 'vol',
        target: { kind: 'trackVolume' as const, trackId: 't1' },
        enabled: true,
        points: [
          { t: 0, v: 0.2 },
          { t: 2.5, v: 0.9 },
        ],
      },
      {
        id: 'stale',
        target: { kind: 'trackPan' as const, trackId: 'deleted' },
        enabled: true,
        points: [{ t: 1, v: -1 }],
      },
    ];
    const wire = JSON.parse(
      JSON.stringify(
        toEditorTimeline(
          { tracks: [track], clips: [], automationLanes },
          'snd',
        ),
      ),
    );
    expect(automationFromTimeline(wire)).toEqual([automationLanes[0]]);
    expect(
      'automation' in toEditorTimeline({ tracks: [track], clips: [] }, 'snd'),
    ).toBe(false);
  });

  it('leaves unbounced MIDI clips out of the server timeline', () => {
    const base = {
      trackId: 't1',
      offsetIntoSource: 0,
      sourceDuration: 4,
      durationSec: 4,
      audioBlob: new Blob(),
      mimeType: 'audio/wav',
      label: 'Clip',
      color: '#abc',
    };
    const timeline = toEditorTimeline(
      {
        tracks: [
          {
            id: 't1',
            name: 'Keys',
            nameAutoGenerated: false,
            volume: 0.8,
            pan: 0,
            mute: false,
            solo: false,
            color: '#abc',
          },
        ],
        clips: [
          { ...base, id: 'audio', startSec: 0, sourceKind: 'audio' },
          {
            ...base,
            id: 'midi',
            startSec: 8,
            sourceKind: 'piano-roll',
            sourcePianoRoll: [],
          },
        ],
      },
      'sound-1',
    );
    expect(timeline.tracks[0]?.clips.map((c) => c.id)).toEqual(['audio']);
    expect(timeline.durationSec).toBe(4);
  });
});
