import type { AudioClip, EditorTrack } from '@tahti-player/audio-editor';

import type {
  EditorTimeline,
  EditorTimelineClip,
  EditorTimelineTrack,
} from '../api/studio-types';

const GAIN_DB_MIN = -24;
const GAIN_DB_MAX = 12;

export function volumeToGainDb(volume: number): number {
  const v = Math.max(1e-4, Math.min(1, volume));
  const db = 20 * Math.log10(v);
  return Math.max(GAIN_DB_MIN, Math.min(GAIN_DB_MAX, Math.round(db)));
}

export function gainDbToVolume(gainDb: number): number {
  const db = Math.max(GAIN_DB_MIN, Math.min(GAIN_DB_MAX, gainDb));
  return Math.max(0, Math.min(1, Math.pow(10, db / 20)));
}

export type EditorStoreSnapshot = {
  tracks: EditorTrack[];
  clips: AudioClip[];
  bpm?: number;
};

/** Serialize the local Multitrack store into the server EditorTimeline shape.
 * FX chains, pan, and audio blobs are OPFS-only and omitted. */
export function toEditorTimeline(
  snapshot: EditorStoreSnapshot,
  defaultSoundId: string,
): EditorTimeline {
  let durationSec = 0;
  const tracks: EditorTimelineTrack[] = snapshot.tracks.map((track, index) => {
    const trackClips = snapshot.clips
      .filter((c) => c.trackId === track.id)
      .map((clip): EditorTimelineClip => {
        const end = clip.startSec + clip.durationSec;
        if (end > durationSec) {
          durationSec = end;
        }
        return {
          id: clip.id,
          sourceSoundId: defaultSoundId,
          startSec: clip.startSec,
          sourceOffsetSec: clip.offsetIntoSource ?? 0,
          durationSec: clip.durationSec,
        };
      });
    return {
      id: track.id,
      name: track.name || `Track ${index + 1}`,
      color: track.color || '#3b82f6',
      gainDb: volumeToGainDb(track.volume ?? 0.8),
      muted: Boolean(track.mute),
      solo: Boolean(track.solo),
      clips: trackClips,
    };
  });
  return {
    version: 1,
    durationSec: Math.max(1, durationSec),
    tracks,
  };
}

export type HydratedClipSeed = {
  trackId: string;
  clip: EditorTimelineClip;
  audioBlob: Blob;
  peaks: number[];
  duration: number;
};

/** Build store tracks from a server timeline (clips need blobs loaded separately). */
export function tracksFromTimeline(
  timeline: EditorTimeline,
): Array<Partial<EditorTrack> & { id: string; name: string }> {
  return timeline.tracks.map((t) => ({
    id: t.id,
    name: t.name,
    color: t.color,
    volume: gainDbToVolume(t.gainDb),
    pan: 0,
    mute: t.muted,
    solo: t.solo,
    nameAutoGenerated: false,
  }));
}

export function timelineHasClips(
  timeline: EditorTimeline | null | undefined,
): boolean {
  return Boolean(timeline?.tracks?.some((t) => t.clips.length > 0));
}
