import type { ExportTarget } from './types';

export const EXPORT_TARGETS: ExportTarget[] = [
  {
    id: 'spotify',
    label: 'Spotify',
    note: 'Storefront deep link — submit releases via Revelator in Studio → Distribution.',
    color: 'var(--accent-green)',
    to: '/studio/distribution',
    supportsTracks: false,
  },
  {
    id: 'apple',
    label: 'Apple Music',
    note: 'Storefront deep link — submit releases via Revelator in Studio → Distribution.',
    color: 'var(--foreground-secondary)',
    to: '/studio/distribution',
    supportsTracks: false,
  },
  {
    id: 'deezer',
    label: 'Deezer',
    note: 'Storefront deep link — submit releases via Revelator in Studio → Distribution.',
    color: 'var(--primary)',
    to: '/studio/distribution',
    supportsTracks: false,
  },
  {
    id: 'youtube',
    label: 'YouTube Music',
    note: 'Storefront deep link — submit releases via Revelator in Studio → Distribution.',
    color: 'var(--accent-red)',
    to: '/studio/distribution',
    supportsTracks: false,
  },
  {
    id: 'bandcamp',
    label: 'Bandcamp',
    note: 'Manage the connected account under Add-ons → Import.',
    color: 'var(--accent-cyan)',
    to: '/settings/plugin-store?category=import',
    supportsTracks: false,
  },
  {
    id: 'soundcloud',
    label: 'SoundCloud',
    note: 'Manage the connected account under Add-ons → Import.',
    color: 'var(--accent-orange)',
    to: '/settings/plugin-store?category=import',
    supportsTracks: false,
  },
  {
    id: 'mixcloud',
    label: 'Mixcloud',
    note: 'Export individual mixes from Track info.',
    color: 'var(--accent-purple)',
    to: '/settings/plugin-store?category=import',
    supportsTracks: true,
  },
  {
    id: 'hearthis',
    label: 'hearthis.at',
    note: 'No push API — cross-post manually using your connected username.',
    color: 'var(--accent-yellow)',
    to: '/settings/plugin-store?category=import',
    supportsTracks: false,
  },
];
