/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PlaylistsRouteImport } from './routes/playlists'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaylistsIndexRouteImport } from './routes/playlists/index'
import { Route as PlaylistsPlaylistIdRouteImport } from './routes/playlists/$playlistId'
import { Route as FavoritesTracksRouteImport } from './routes/favorites/tracks'
import { Route as FavoritesArtistsRouteImport } from './routes/favorites/artists'
import { Route as FavoritesAlbumsRouteImport } from './routes/favorites/albums'
import { Route as PlaylistsImportProviderIdRouteImport } from './routes/playlists/import.$providerId'
import { Route as ArtistProviderIdArtistIdRouteImport } from './routes/artist/$providerId/$artistId'
import { Route as AlbumProviderIdAlbumIdRouteImport } from './routes/album/$providerId/$albumId'

const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsRoute = PlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsIndexRoute = PlaylistsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlaylistsRoute,
} as any)
const PlaylistsPlaylistIdRoute = PlaylistsPlaylistIdRouteImport.update({
  id: '/$playlistId',
  path: '/$playlistId',
  getParentRoute: () => PlaylistsRoute,
} as any)
const FavoritesTracksRoute = FavoritesTracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => FavoritesRoute,
} as any)
const FavoritesArtistsRoute = FavoritesArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => FavoritesRoute,
} as any)
const FavoritesAlbumsRoute = FavoritesAlbumsRouteImport.update({
  id: '/albums',
  path: '/albums',
  getParentRoute: () => FavoritesRoute,
} as any)
const PlaylistsImportProviderIdRoute =
  PlaylistsImportProviderIdRouteImport.update({
    id: '/import/$providerId',
    path: '/import/$providerId',
    getParentRoute: () => PlaylistsRoute,
  } as any)
const ArtistProviderIdArtistIdRoute =
  ArtistProviderIdArtistIdRouteImport.update({
    id: '/artist/$providerId/$artistId',
    path: '/artist/$providerId/$artistId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AlbumProviderIdAlbumIdRoute = AlbumProviderIdAlbumIdRouteImport.update({
  id: '/album/$providerId/$albumId',
  path: '/album/$providerId/$albumId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRouteWithChildren
  '/history': typeof HistoryRoute
  '/playlists': typeof PlaylistsRouteWithChildren
  '/search': typeof SearchRoute
  '/sources': typeof SourcesRoute
  '/favorites/albums': typeof FavoritesAlbumsRoute
  '/favorites/artists': typeof FavoritesArtistsRoute
  '/favorites/tracks': typeof FavoritesTracksRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/playlists/': typeof PlaylistsIndexRoute
  '/album/$providerId/$albumId': typeof AlbumProviderIdAlbumIdRoute
  '/artist/$providerId/$artistId': typeof ArtistProviderIdArtistIdRoute
  '/playlists/import/$providerId': typeof PlaylistsImportProviderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRouteWithChildren
  '/history': typeof HistoryRoute
  '/search': typeof SearchRoute
  '/sources': typeof SourcesRoute
  '/favorites/albums': typeof FavoritesAlbumsRoute
  '/favorites/artists': typeof FavoritesArtistsRoute
  '/favorites/tracks': typeof FavoritesTracksRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/playlists': typeof PlaylistsIndexRoute
  '/album/$providerId/$albumId': typeof AlbumProviderIdAlbumIdRoute
  '/artist/$providerId/$artistId': typeof ArtistProviderIdArtistIdRoute
  '/playlists/import/$providerId': typeof PlaylistsImportProviderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRouteWithChildren
  '/history': typeof HistoryRoute
  '/playlists': typeof PlaylistsRouteWithChildren
  '/search': typeof SearchRoute
  '/sources': typeof SourcesRoute
  '/favorites/albums': typeof FavoritesAlbumsRoute
  '/favorites/artists': typeof FavoritesArtistsRoute
  '/favorites/tracks': typeof FavoritesTracksRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/playlists/': typeof PlaylistsIndexRoute
  '/album/$providerId/$albumId': typeof AlbumProviderIdAlbumIdRoute
  '/artist/$providerId/$artistId': typeof ArtistProviderIdArtistIdRoute
  '/playlists/import/$providerId': typeof PlaylistsImportProviderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/favorites'
    | '/history'
    | '/playlists'
    | '/search'
    | '/sources'
    | '/favorites/albums'
    | '/favorites/artists'
    | '/favorites/tracks'
    | '/playlists/$playlistId'
    | '/playlists/'
    | '/album/$providerId/$albumId'
    | '/artist/$providerId/$artistId'
    | '/playlists/import/$providerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/favorites'
    | '/history'
    | '/search'
    | '/sources'
    | '/favorites/albums'
    | '/favorites/artists'
    | '/favorites/tracks'
    | '/playlists/$playlistId'
    | '/playlists'
    | '/album/$providerId/$albumId'
    | '/artist/$providerId/$artistId'
    | '/playlists/import/$providerId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/favorites'
    | '/history'
    | '/playlists'
    | '/search'
    | '/sources'
    | '/favorites/albums'
    | '/favorites/artists'
    | '/favorites/tracks'
    | '/playlists/$playlistId'
    | '/playlists/'
    | '/album/$providerId/$albumId'
    | '/artist/$providerId/$artistId'
    | '/playlists/import/$providerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  FavoritesRoute: typeof FavoritesRouteWithChildren
  HistoryRoute: typeof HistoryRoute
  PlaylistsRoute: typeof PlaylistsRouteWithChildren
  SearchRoute: typeof SearchRoute
  SourcesRoute: typeof SourcesRoute
  AlbumProviderIdAlbumIdRoute: typeof AlbumProviderIdAlbumIdRoute
  ArtistProviderIdArtistIdRoute: typeof ArtistProviderIdArtistIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists': {
      id: '/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof PlaylistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/': {
      id: '/playlists/'
      path: '/'
      fullPath: '/playlists/'
      preLoaderRoute: typeof PlaylistsIndexRouteImport
      parentRoute: typeof PlaylistsRoute
    }
    '/playlists/$playlistId': {
      id: '/playlists/$playlistId'
      path: '/$playlistId'
      fullPath: '/playlists/$playlistId'
      preLoaderRoute: typeof PlaylistsPlaylistIdRouteImport
      parentRoute: typeof PlaylistsRoute
    }
    '/favorites/tracks': {
      id: '/favorites/tracks'
      path: '/tracks'
      fullPath: '/favorites/tracks'
      preLoaderRoute: typeof FavoritesTracksRouteImport
      parentRoute: typeof FavoritesRoute
    }
    '/favorites/artists': {
      id: '/favorites/artists'
      path: '/artists'
      fullPath: '/favorites/artists'
      preLoaderRoute: typeof FavoritesArtistsRouteImport
      parentRoute: typeof FavoritesRoute
    }
    '/favorites/albums': {
      id: '/favorites/albums'
      path: '/albums'
      fullPath: '/favorites/albums'
      preLoaderRoute: typeof FavoritesAlbumsRouteImport
      parentRoute: typeof FavoritesRoute
    }
    '/playlists/import/$providerId': {
      id: '/playlists/import/$providerId'
      path: '/import/$providerId'
      fullPath: '/playlists/import/$providerId'
      preLoaderRoute: typeof PlaylistsImportProviderIdRouteImport
      parentRoute: typeof PlaylistsRoute
    }
    '/artist/$providerId/$artistId': {
      id: '/artist/$providerId/$artistId'
      path: '/artist/$providerId/$artistId'
      fullPath: '/artist/$providerId/$artistId'
      preLoaderRoute: typeof ArtistProviderIdArtistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$providerId/$albumId': {
      id: '/album/$providerId/$albumId'
      path: '/album/$providerId/$albumId'
      fullPath: '/album/$providerId/$albumId'
      preLoaderRoute: typeof AlbumProviderIdAlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FavoritesRouteChildren {
  FavoritesAlbumsRoute: typeof FavoritesAlbumsRoute
  FavoritesArtistsRoute: typeof FavoritesArtistsRoute
  FavoritesTracksRoute: typeof FavoritesTracksRoute
}

const FavoritesRouteChildren: FavoritesRouteChildren = {
  FavoritesAlbumsRoute: FavoritesAlbumsRoute,
  FavoritesArtistsRoute: FavoritesArtistsRoute,
  FavoritesTracksRoute: FavoritesTracksRoute,
}

const FavoritesRouteWithChildren = FavoritesRoute._addFileChildren(
  FavoritesRouteChildren,
)

interface PlaylistsRouteChildren {
  PlaylistsPlaylistIdRoute: typeof PlaylistsPlaylistIdRoute
  PlaylistsIndexRoute: typeof PlaylistsIndexRoute
  PlaylistsImportProviderIdRoute: typeof PlaylistsImportProviderIdRoute
}

const PlaylistsRouteChildren: PlaylistsRouteChildren = {
  PlaylistsPlaylistIdRoute: PlaylistsPlaylistIdRoute,
  PlaylistsIndexRoute: PlaylistsIndexRoute,
  PlaylistsImportProviderIdRoute: PlaylistsImportProviderIdRoute,
}

const PlaylistsRouteWithChildren = PlaylistsRoute._addFileChildren(
  PlaylistsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  FavoritesRoute: FavoritesRouteWithChildren,
  HistoryRoute: HistoryRoute,
  PlaylistsRoute: PlaylistsRouteWithChildren,
  SearchRoute: SearchRoute,
  SourcesRoute: SourcesRoute,
  AlbumProviderIdAlbumIdRoute: AlbumProviderIdAlbumIdRoute,
  ArtistProviderIdArtistIdRoute: ArtistProviderIdArtistIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
