import { useCallback, useEffect, useRef, useState } from 'react';
import { toast } from 'sonner';

import { preferInternalEngine } from '@tahti-player/audio-core';
import {
  computePeaks,
  loadBlobOntoNewTrack,
  useEditorStore,
} from '@tahti-player/audio-editor';

import {
  createEditorProject,
  fetchEditorProject,
  fetchEditorProjects,
  fetchEditorStreamBlob,
  updateEditorProject,
  type StemJob,
} from '../../api/studio';
import type { EditorTimeline } from '../../api/studio-types';
import {
  timelineHasClips,
  toEditorTimeline,
  tracksFromTimeline,
} from '../../lib/editorTimelineAdapter';
import { sendStemFilesToMultitrack } from '../../lib/stemsToMultitrack';

const SESSION_SYNC_DEBOUNCE_MS = 1200;

export type MultitrackSessionSync = 'idle' | 'syncing' | 'synced' | 'local';

async function hydrateFromTimeline(
  timeline: EditorTimeline,
  fallbackSoundId: string,
): Promise<boolean> {
  const trackSeeds = tracksFromTimeline(timeline);
  if (!trackSeeds.length) {
    return false;
  }
  const blobCache = new Map<string, Blob>();
  const clips: Array<{
    trackId: string;
    startSec: number;
    durationSec: number;
    offsetIntoSource: number;
    sourceDuration: number;
    audioBlob: Blob;
    mimeType: string;
    peaks: Float32Array;
    label: string;
    color: string;
    sourceKind: 'audio';
    id: string;
  }> = [];

  for (const track of timeline.tracks) {
    for (const clip of track.clips) {
      const srcId = clip.sourceSoundId || fallbackSoundId;
      let blob = blobCache.get(srcId);
      if (!blob) {
        blob = await fetchEditorStreamBlob(srcId);
        blobCache.set(srcId, blob);
      }
      const { peaks, duration } = await computePeaks(blob, 240);
      clips.push({
        id: clip.id,
        trackId: track.id,
        startSec: clip.startSec,
        durationSec: clip.durationSec,
        offsetIntoSource: clip.sourceOffsetSec,
        sourceDuration: Math.max(
          duration,
          clip.sourceOffsetSec + clip.durationSec,
        ),
        audioBlob: blob,
        mimeType: blob.type || 'audio/wav',
        peaks,
        label: track.name,
        color: track.color || '#3b82f6',
        sourceKind: 'audio',
      });
    }
  }

  useEditorStore.getState().loadProject({
    tracks: trackSeeds.map((t) => ({
      id: t.id,
      name: t.name,
      nameAutoGenerated: false,
      volume: t.volume ?? 0.8,
      pan: t.pan ?? 0,
      mute: t.mute ?? false,
      solo: t.solo ?? false,
      color: t.color || '#3b82f6',
    })),
    clips,
  });
  return clips.length > 0;
}

export function useMultitrackSession({
  soundId,
  title,
  editorMode,
  setEditorMode,
  setBusy,
}: {
  soundId: string;
  title: string;
  editorMode: 'trim' | 'multitrack';
  setEditorMode: (mode: 'trim' | 'multitrack') => void;
  setBusy: (busy: boolean) => void;
}) {
  const [multitrackReady, setMultitrackReady] = useState(false);
  const [editorProjectId, setEditorProjectId] = useState<string | null>(null);
  const [sessionSync, setSessionSync] = useState<MultitrackSessionSync>('idle');
  const sessionSaveTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  const persistSession = useCallback(async () => {
    if (!editorProjectId) {
      return;
    }
    const st = useEditorStore.getState();
    const timeline = toEditorTimeline(
      { tracks: st.tracks, clips: st.clips, bpm: st.bpm },
      soundId,
    );
    setSessionSync('syncing');
    const result = await updateEditorProject(editorProjectId, timeline);
    if (result.ok) {
      setSessionSync('synced');
    } else {
      setSessionSync('local');
    }
  }, [editorProjectId, soundId]);

  const ensureMultitrackSession = useCallback(async () => {
    preferInternalEngine();
    setSessionSync('syncing');
    try {
      const listed = await fetchEditorProjects();
      let project = listed.data.find((row) => row.soundId === soundId) ?? null;
      if (!project) {
        const created = await createEditorProject({
          soundId,
          title: title || 'Multitrack session',
        });
        if (!created.ok) {
          throw new Error(created.error);
        }
        project = created.data;
      }
      setEditorProjectId(project.id);

      const detail = await fetchEditorProject(project.id);
      const timeline = detail.data.timeline ?? null;
      if (timelineHasClips(timeline) && timeline) {
        const ok = await hydrateFromTimeline(timeline, soundId);
        if (ok) {
          setMultitrackReady(true);
          setSessionSync(
            detail.meta.source === 'api' || detail.meta.source === 'mock'
              ? 'synced'
              : 'local',
          );
          return;
        }
      }

      useEditorStore.getState().loadProject({ tracks: [], clips: [] });
      const blob = await fetchEditorStreamBlob(soundId);
      await loadBlobOntoNewTrack(blob, title || 'Source');
      setMultitrackReady(true);
      await updateEditorProject(
        project.id,
        toEditorTimeline(
          {
            tracks: useEditorStore.getState().tracks,
            clips: useEditorStore.getState().clips,
          },
          soundId,
        ),
      );
      setSessionSync('synced');
    } catch {
      setSessionSync('local');
      toast.error('Could not load audio into the multitrack editor.');
      try {
        useEditorStore.getState().loadProject({ tracks: [], clips: [] });
        const blob = await fetchEditorStreamBlob(soundId);
        await loadBlobOntoNewTrack(blob, title || 'Source');
        setMultitrackReady(true);
      } catch {
        /* already toasted */
      }
    }
  }, [soundId, title]);

  const sendStemsToMultitrack = useCallback(
    async (job: StemJob) => {
      if (!job.files?.length) {
        toast.error('This stem job has no files yet.');
        return;
      }
      preferInternalEngine();
      setEditorMode('multitrack');
      setBusy(true);
      try {
        let projectId = editorProjectId;
        if (!projectId) {
          const listed = await fetchEditorProjects();
          let project =
            listed.data.find((row) => row.soundId === soundId) ?? null;
          if (!project) {
            const created = await createEditorProject({
              soundId,
              title: title || 'Multitrack session',
            });
            if (!created.ok) {
              toast.error(created.error);
              return;
            }
            project = created.data;
          }
          projectId = project.id;
          setEditorProjectId(projectId);
        }

        const result = await sendStemFilesToMultitrack(job.files);
        if (!result.ok) {
          toast.error(result.error);
          return;
        }
        setMultitrackReady(true);
        toast.success(
          `Loaded ${result.trackIds.length} stem lanes into Multitrack.`,
        );
        const st = useEditorStore.getState();
        await updateEditorProject(
          projectId,
          toEditorTimeline(
            { tracks: st.tracks, clips: st.clips, bpm: st.bpm },
            soundId,
          ),
        );
        setSessionSync('synced');
      } catch {
        setSessionSync('local');
        toast.error('Could not send stems to Multitrack.');
      } finally {
        setBusy(false);
      }
    },
    [editorProjectId, setBusy, setEditorMode, soundId, title],
  );

  useEffect(() => {
    if (editorMode !== 'multitrack' || !editorProjectId) {
      return;
    }
    const unsub = useEditorStore.subscribe(() => {
      if (sessionSaveTimer.current) {
        clearTimeout(sessionSaveTimer.current);
      }
      sessionSaveTimer.current = setTimeout(() => {
        void persistSession();
      }, SESSION_SYNC_DEBOUNCE_MS);
    });
    return () => {
      unsub();
      if (sessionSaveTimer.current) {
        clearTimeout(sessionSaveTimer.current);
      }
    };
  }, [editorMode, editorProjectId, persistSession]);

  return {
    multitrackReady,
    editorProjectId,
    sessionSync,
    persistSession,
    ensureMultitrackSession,
    sendStemsToMultitrack,
  };
}
