import { describe, expect, it } from 'vitest';

import { newChainEntry } from '@tahti-player/audio-rack';

import {
  sampleLane,
  useEditorStore,
  type AutomationLane,
  type EditorTrack,
} from '../state/editorStore';
import {
  AUTOMATION_SYNC_MAX_BYTES,
  fxWriteTimes,
  laneParamEvents,
  parseAutomation,
  scheduleLaneOnParam,
  serializeAutomation,
  trackFxAutomationParam,
  VOLUME_RANGE,
} from './automation';

const lane = (
  points: Array<[number, number]>,
  overrides: Partial<AutomationLane> = {},
): AutomationLane => ({
  id: 'lane-1',
  target: { kind: 'trackVolume', trackId: 't1' },
  enabled: true,
  points: points.map(([t, v]) => ({ t, v })),
  ...overrides,
});

const track = (overrides: Partial<EditorTrack> = {}): EditorTrack => ({
  id: 't1',
  name: 'Lead',
  nameAutoGenerated: false,
  volume: 0.8,
  pan: 0,
  mute: false,
  solo: false,
  color: '#3b82f6',
  ...overrides,
});

describe('breakpoint interpolation', () => {
  const l = lane([
    [1, 0],
    [3, 1],
    [5, 0.5],
  ]);

  it('holds the first and last values outside the breakpoints', () => {
    expect(sampleLane(l, 0)).toBe(0);
    expect(sampleLane(l, 9)).toBe(0.5);
  });

  it('interpolates linearly between neighbors', () => {
    expect(sampleLane(l, 2)).toBeCloseTo(0.5, 6);
    expect(sampleLane(l, 4)).toBeCloseTo(0.75, 6);
  });

  it('is null for a lane without points', () => {
    expect(sampleLane(lane([]), 2)).toBeNull();
  });

  it('turns the lane into a set under the playhead and ramps after it', () => {
    expect(laneParamEvents(l, 2)).toEqual([
      { type: 'set', at: 0, v: 0.5 },
      { type: 'ramp', at: 1, v: 1 },
      { type: 'ramp', at: 3, v: 0.5 },
    ]);
    expect(laneParamEvents(l, 6)).toEqual([{ type: 'set', at: 0, v: 0.5 }]);
  });

  it('writes clamped events onto an AudioParam at context time', () => {
    const calls: string[] = [];
    const param = {
      cancelScheduledValues: (t: number) => calls.push(`cancel ${t}`),
      setValueAtTime: (v: number, t: number) => calls.push(`set ${v} @${t}`),
      linearRampToValueAtTime: (v: number, t: number) =>
        calls.push(`ramp ${v} @${t}`),
    } as unknown as AudioParam;
    scheduleLaneOnParam(
      param,
      lane([
        [0, 2],
        [2, -1],
      ]),
      0,
      10,
      VOLUME_RANGE,
    );
    expect(calls).toEqual(['cancel 0', 'set 1 @10', 'ramp 0 @12']);
  });

  it('steps offline FX writes across the breakpoint span only', () => {
    expect(
      fxWriteTimes(
        lane([
          [1, 0],
          [1.1, 1],
        ]),
        0.05,
        10,
      ).map((t) => Math.round(t * 100) / 100),
    ).toEqual([1, 1.05, 1.1]);
    expect(fxWriteTimes(lane([[1, 0]]), 0.05, 10)).toEqual([]);
  });
});

describe('automation serialization', () => {
  const lanes: AutomationLane[] = [
    lane([
      [0, 0.25],
      [1.23456, 0.987654],
    ]),
    lane(
      [
        [0.5, -1],
        [2, 1],
      ],
      {
        id: 'lane-2',
        target: { kind: 'trackPan', trackId: 't1' },
        enabled: false,
      },
    ),
    lane([[0, 0.3]], {
      id: 'lane-3',
      target: {
        kind: 'trackFx',
        trackId: 't2',
        entryId: 'fx1',
        paramKey: 'mix',
      },
    }),
  ];

  it('round-trips lanes through JSON', () => {
    const wire = JSON.parse(JSON.stringify(serializeAutomation(lanes)));
    const back = parseAutomation(wire);
    expect(back).toHaveLength(3);
    expect(back[0].points[1]).toEqual({ t: 1.235, v: 0.9877 });
    expect(back[1]).toMatchObject({
      id: 'lane-2',
      enabled: false,
      target: { kind: 'trackPan', trackId: 't1' },
    });
    expect(back[2].target).toEqual({
      kind: 'trackFx',
      trackId: 't2',
      entryId: 'fx1',
      paramKey: 'mix',
    });
  });

  it('skips empty lanes and returns null when there is nothing to sync', () => {
    expect(serializeAutomation([lane([])])).toBeNull();
  });

  it('returns null rather than exceeding the metadata budget', () => {
    const many = Array.from({ length: 40 }, (_, i) =>
      lane(
        Array.from({ length: 4000 }, (_, j): [number, number] => [
          j * 0.123457,
          0.123457,
        ]),
        { id: `lane-${i}` },
      ),
    );
    expect(serializeAutomation(many)).toBeNull();
    expect(AUTOMATION_SYNC_MAX_BYTES).toBeLessThan(500_000);
  });

  it('drops malformed input and lanes for unknown tracks', () => {
    expect(parseAutomation(null)).toEqual([]);
    expect(parseAutomation({ lanes: 'nope' })).toEqual([]);
    const back = parseAutomation(
      {
        version: 1,
        lanes: [
          { id: 'a', target: { kind: 'bogus' }, points: [[0, 1]] },
          {
            id: 'b',
            target: { kind: 'trackVolume', trackId: 't1' },
            points: [
              [2, 1],
              ['x', 0],
              [-1, 0],
              [1, 0.5],
            ],
          },
          {
            id: 'c',
            target: { kind: 'trackVolume', trackId: 'gone' },
            points: [[0, 1]],
          },
        ],
      },
      new Set(['t1']),
    );
    expect(back).toEqual([
      {
        id: 'b',
        target: { kind: 'trackVolume', trackId: 't1' },
        enabled: true,
        points: [
          { t: 1, v: 0.5 },
          { t: 2, v: 1 },
        ],
      },
    ]);
  });
});

describe('loadProject with automation', () => {
  it('keeps lanes for loaded tracks and drops orphans', () => {
    useEditorStore.getState().loadProject({
      tracks: [track()],
      clips: [],
      automationLanes: [
        lane([[0, 0.5]]),
        lane([[0, 0.5]], {
          id: 'orphan',
          target: { kind: 'trackPan', trackId: 'missing' },
        }),
      ],
    });
    expect(useEditorStore.getState().automationLanes.map((l) => l.id)).toEqual([
      'lane-1',
    ]);
    useEditorStore.getState().loadProject({ tracks: [], clips: [] });
    expect(useEditorStore.getState().automationLanes).toEqual([]);
  });
});

describe('trackFxAutomationParam', () => {
  it('picks the first enabled rack effect wet/dry or continuous param', () => {
    expect(trackFxAutomationParam(track())).toBeNull();
    const entry = newChainEntry('reverb', {});
    const param = trackFxAutomationParam(track({ fxChain: [entry] }));
    expect(param?.entryId).toBe(entry.id);
    expect(param?.range.max).toBeGreaterThan(param?.range.min ?? 0);
    expect(
      trackFxAutomationParam(
        track({ fxChain: [{ ...entry, enabled: false }] }),
      ),
    ).toBeNull();
  });
});
